pipeline {
  agent {
      dockerfile true
      // Tentukan path ke Dockerfile yang diinginkan
      args '-f Dockerfile1'  // Misalnya ingin menggunakan Dockerfile1
  }
  stages {
    stage('Test') {
      steps {
        sh '''
          node --version
          git --version
          curl --version
        '''
      }
    }
  }
}